# Generated by Django 5.2.8 on 2025-11-25 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'task_manager_category',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In_progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='New', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task_manager_task',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('title',), name='unique_task_title')],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In_progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.task')),
            ],
            options={
                'verbose_name': 'SubTask',
                'verbose_name_plural': 'SubTasks',
                'db_table': 'task_manager_subtask',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('title',), name='unique_subtask_title')],
            },
        ),
    ]
